### PR TITLE
Added DateTime the entry was added to offenders

### LINKED ISSUE #9: Date the entry was added to PTO
I would like to be able to see when each entry was added to the PTO list. 

Currently this is only possible by getting the post URL to the specific entry, opening it and checking the date the post was created. Doing so automatically would be roughly 4000 hits. I could keep a local copy of already checked URLs so it would only be 4000 hits the first time and just a few every subsequent time, but still as soon as the blog's template changes the scrabber would fail.

As a simpler solution I would suggest adding a 3rd column "date added" to offender.csv.

I would even add the date to all existing entries myself if I can get the okay to add a third column.

### PR DESCRIPTION
**Pull request by LunaLycan287**
Fixes [plaintextoffenders/#9](https://github.com/plaintextoffenders/plaintextoffenders/issues/9)
Requires [plaintextoffenders/pull/#10](https://github.com/plaintextoffenders/plaintextoffenders/pull/10)
Added DateTime field to Update script
- It was decided that Tumblrs date field should be used for human readability
Added handling to update duplicate offenders
- If a offender is duplicate only the one with the newer post date will be kept

### CODE REVIEW

**Comment by LunaLycan287** [comment]
Please Review. This is pretty much only my second time working with python at all.

**Comment by aviemzur** [comment]
Hi, sorry for the delay, will review ASAP

**Comment by Alonreznik** [comment]
Hi @aviemzur @Moonwolf287.
Both codes (master+pull-request) are kind of complicated and don't use the python csv reader, for example. I'm rewriting the code to be more easy to manage and use, including the datetime filtering by @Moonwolf287  and I'll make a pull request for that.

Thank you for your adding. 
I'm closing this PR and will be merged into a new one, based on this.

Alon

**Comment by Alonreznik** [comment]
I've reopened the pull request in order to make my code based on @Moonwolf287 logic.
Please merge it, and then merge fixes in https://github.com/plaintextoffenders/pto-scripts/pull/3

**Comment by aviemzur** [comment]
Code merged through pr/3

**Pull request closed without merging**
